### PR TITLE
Graphs

### LINKED ISSUE #51: [UC 4.2] As an ADMIN I want to see SO scores by course level so that I can analyze whether SOs are improving toward upper-level classes.

### PR DESCRIPTION
**Pull request by mdjohns**
This PR adds the recharts library for integrating graphs into DCIA. I'm getting close to completing my work on this branch and wanted to get some eyes on it now.

**Summary:**
- Created a generic `LineGraph` component
- Dashboard has been re-worked to include an `AdminDashboard` component to wrap all the components from the term selector down. This component fetches terms to populate the term selector and the selected term is used for the other components to make their own data requests.
- Created a new endpoint "directory" `/api/analysis` to encapsulate the endpoints needed for our analysis features. `/api/analysis/terms` gets terms to for the term selector and a dynamic route populates the graphs at `/api/analysis/scores_by/[filter]` 

**TODO:**
- Integrate live data and real queries on the backend
- ScoresByTerm chart and its endpoint. This is a bit of a hurdle because of the combinations of filter options, but I'm working on this today.
- Protect API endpoints.
- Lots of linting errors to still resolve.
- Potentially add another prop to `LineGraph` to add tooltips to the legend. Looking at the scores by level graph, it seems like it would be helpful to have that mouse-over description of each SO like the SOs page.

Should close #51, #52, #53, #54

### CODE REVIEW

**Comment by mdjohns** [comment]
@jcypret 
I made some more progress on the Scores By Term chart. SWR fetching is working, although we're not fetching dynamic data yet. Just filled it with some dummy data for now to make sure my mental model of the data worked. 

Still need to implement those bar charts and integrate the query data, but I'm getting closer.

**Comment by mdjohns** [comment]
:stop_sign: This is not ready for review at this time.

Implementing new changes from Zoom discussion today, will update when it's in a good place.

**Review by jcypret — COMMENTED** [review]
I pulled the branch down and did some click-testing and was really nice to see everything coming together! No major blockers from me.

I was wondering on the charts; it looks like everything currently rounded to integer… is that just for the test data? I was thinking "Scores by Term" and "… Level" charts would have values rounded to the nearest 10th, similar to the scores by course and instructor.

Secondly, the period select (which is working awesome 💪!) is currently defaulting to Spring 2020, but the `isCurrent` flag in the database is set to Fall 2020… is that expected?

**Comment by mdjohns** [comment]
Everything you're seeing is all faked data at this point, just to make sure the UI was doing what it was supposed to. So the term selector isn't pulling from the database yet (though I just finished that functionality locally). Same for the graphs, not sure why I didn't use floats for the test data, but it's all fake :joy: 

Now that the real data and queries have hit main, I'm working on integrating all of that right now.

**Comment by mdjohns** [comment]
3d0adb9 will close #57 as well

**Comment by mdjohns** [comment]
@jcypret this is most of the way there. looking at the bar graph alignment issue now, but would love some eyes!

**Review by jcypret — APPROVED** [review]
LGTM! 🧨

**Pull request merged**
