### PR TITLE
Query files

### PR DESCRIPTION
**Pull request by I-am-Scott-White**
Alterations made to match models and seeders

### CODE REVIEW

**Comment by mdjohns** [comment]
I'll run these and make sure the results still look good tonight.

The e2e tests appear to be failing again, so we'll need to determine the cause of that to make sure we're not introducing any issues into `main`

**Comment by jcypret** [comment]
Fixed conflicts and merged in the other queries PR but wasn't sure about this one… looks like some version of these files already exists on main?

**Comment by I-am-Scott-White** [comment]
Dylan had merged these before but I had to make alterations to all of these files. I am not sure what the e2e failure is in Cypress with registration and signin is.

**Comment by mdjohns** [comment]
I'm looking at this now. I think this PR should just cover query changes RE: [this comment](https://github.com/ualr-htcpcp/dcia/pull/58#discussion_r536383726) on the other PR.

**Comment by I-am-Scott-White** [comment]
Would making the alterations you linked fix this issue?

**Comment by mdjohns** [comment]
Re-packaged the query changes back into their appropriate JS files. E2E ran successfully locally and it looks like it passed the GH action as well.

**Pull request merged**
